version: "3.9"
services:
  backend:
    build: ./backend
    working_dir: /backend/backend
    volumes:
      - ./:/backend
    links:
      - db
    ports:
      - 127.0.0.1:8089:8000
    depends_on:
      db:
        condition: service_healthy
  ui:
    build: ./frontend
    working_dir: /ui/frontend
    volumes:
      - ./:/ui
    links:
      - backend
    ports:
      - 127.0.0.1:3000:3000
  db:
    image: mysql
    healthcheck:
      test: [ "CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-psomesecurepwd' ]
      timeout: 20s
      retries: 10
    ports:
      - 127.0.0.1:33066:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: somesecurepwd
      MYSQL_DATABASE: db
      MYSQL_ROOT_HOST: '%'